services:
  - type: web
    name: conxian-ui
    env: node
    plan: free
    buildCommand: "pnpm install && pnpm run build"
    startCommand: "pnpm start"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "1"
      - key: NEXT_PUBLIC_CORE_API_URL
        value: https://api.testnet.hiro.so
